apiVersion: 1
kind: Dataset
content:
  id: ca.vancouver.opendata.rapid-transit.stations
  rootPollingSource:
    fetch:
      kind: fetchUrl
      url: ftp://webftp.vancouver.ca/OpenData/shape/shape_rapid_transit.zip
    read:
      kind: shapefile
      subPathRegex: rapid_transit_stations.*
    preprocess:
      - view: output
        query: >
          SELECT
            ST_Transform(geometry, "epsg:3157", "epsg:4326") as geometry,
            STATION
          FROM input
    merge:
      # TODO
      kind: append