apiVersion: 1
kind: DatasetSnapshot
content:
  id: ca.vancouver.opendata.rapid-transit.stations
  source:
    kind: root
    fetch:
      kind: url
      url: ftp://webftp.vancouver.ca/OpenData/shape/shape_rapid_transit.zip
    read:
      kind: esriShapefile
      subPath: rapid_transit_stations.*
    preprocess:
      engine: sparkSQL
      query: >
        SELECT
          ST_Transform(geometry, "epsg:3157", "epsg:4326") as geometry,
          STATION
        FROM input
    merge:
      # TODO
      kind: append