apiVersion: 1
kind: DatasetSnapshot
content:
  id: ca.vancouver.opendata.rapid-transit.lines
  rootPollingSource:
    fetch:
      kind: fetchUrl
      url: ftp://webftp.vancouver.ca/OpenData/shape/shape_rapid_transit.zip
    read:
      kind: shapefile
      subPathRegex: rapid_transit_line.*
    preprocess:
    - kind: sparkSQL
      query: >
        SELECT
          ST_Transform(geometry, "epsg:3157", "epsg:4326") as geometry,
          LINE
        FROM input
    merge:
      # TODO
      kind: append
