apiVersion: 1
kind: DatasetSnapshot
content:
  id: ca.vancouver.opendata.property.local-area-boundaries
  source:
    kind: root
    fetch:
      kind: url
      url: https://opendata.vancouver.ca/explore/dataset/local-area-boundary/download/?format=shp&timezone=America/Los_Angeles&lang=en
    read:
      kind: esriShapefile
    preprocess:
      kind: sql
      engine: spark
      query: >
        SELECT
          ST_Transform(geometry, "epsg:3157", "epsg:4326") as geometry,
          MAPID,
          NAME
        FROM input
    merge:
      # TODO
      kind: append
