apiVersion: 1
kind: Dataset
content:
  id: ca.vancouver.opendata.property.local-area-boundaries
  rootPollingSource:
    fetch:
      kind: fetchUrl
      url: ftp://webftp.vancouver.ca/OpenData/shape/local_area_boundary_shp.zip
    read:
      kind: shapefile
    preprocess:
      - view: output
        query: >
          SELECT
            ST_Transform(geometry, "epsg:3157", "epsg:4326") as geometry,
            MAPID,
            NAME
          FROM input
    merge:
      # TODO
      kind: append
