apiVersion: 1
kind: Dataset
content:
  id: ca.vancouver.opendata.schools
  rootPollingSource:
    fetch:
      kind: fetchUrl
      url: https://opendata.vancouver.ca/explore/dataset/schools/download/?format=csv&timezone=America/Los_Angeles&use_labels_for_header=true
    read:
      kind: csv
      header: true
      delimiter: ';'
      quote: '"'
      escape: '"'
      nullValue: ''
    preprocess:
    - view: output
      query: >
        SELECT
          address,
          school_category,
          school_name,
          ST_GeomFromGeoJSON(geom) as geom,
          geo_local_area
        FROM input
    merge:
      kind: snapshot
      primaryKey:
      - school_name