apiVersion: 1
kind: Dataset
content:
  id: com.naturalearthdata.countries.admin0
  derivativeSource:
    inputs:
      - id: com.naturalearthdata.countries.10m.admin0
      - id: com.naturalearthdata.countries.50m.admin0
        mode: batch
      - id: com.naturalearthdata.countries.110m.admin0
        mode: batch
    steps:
      - view: com.naturalearthdata.countries.admin0
        query: >
          SELECT
            c10.admin,
            c10.iso_a2,
            c10.iso_a3,
            c10.geometry as geometry_10m,
            c10.geojson as geojson_10m,
            c50.geometry as geometry_50m,
            c50.geojson as geojson_50m,
            c110.geometry as geometry_110m,
            c110.geojson as geojson_110m
          FROM `com.naturalearthdata.countries.10m.admin0` as c10
          LEFT JOIN `com.naturalearthdata.countries.50m.admin0` as c50
            ON c10.admin = c50.admin
          LEFT JOIN `com.naturalearthdata.countries.50m.admin0` as c110
            ON c10.admin = c110.admin
