apiVersion: 1
kind: DatasetSnapshot
content:
  id: ca.vancouver.opendata.property.parcel-polygons
  rootPollingSource:
    fetch:
      kind: fetchUrl
      url: ftp://webftp.vancouver.ca/OpenData/shape/shape_property_information.zip
    read:
      kind: shapefile
      subPathRegex: property_parcel_polygons.*
    preprocess:
      - kind: sparkSQL
        query: >
          SELECT
            ST_Transform(geometry, "epsg:3157", "epsg:4326") as geometry,
            CAST(SITE_ID as LONG) as SITE_ID,
            CAST(CIVIC_NO as LONG) as CIVIC_NO,
            CAST(TAX_COORD as LONG) as TAX_COORD,
            STREETNAME
          FROM input
    merge:
      # TODO
      kind: append
