apiVersion: 1
kind: DatasetSnapshot
content:
  id: ca.vancouver.opendata.property.tax-report
  source:
    kind: derivative
    inputs:
      - ca.vancouver.opendata.property.tax-report.2006-2010
      - ca.vancouver.opendata.property.tax-report.2011-2015
      - ca.vancouver.opendata.property.tax-report.2016-2019
      - ca.vancouver.opendata.property.tax-report.2020-now
    transform:
      kind: sql
      engine: spark
      query: >
        SELECT
          PID,
          REPORT_YEAR,
          LEGAL_TYPE,
          FOLIO,
          LAND_COORDINATE,
          ZONING_DISTRICT,
          ZONING_CLASSIFICATION,
          LOT,
          PLAN,
          BLOCK,
          DISTRICT_LOT,
          FROM_CIVIC_NUMBER,
          TO_CIVIC_NUMBER,
          STREET_NAME,
          PROPERTY_POSTAL_CODE,
          NARRATIVE_LEGAL_LINE1,
          NARRATIVE_LEGAL_LINE2,
          NARRATIVE_LEGAL_LINE3,
          NARRATIVE_LEGAL_LINE4,
          NARRATIVE_LEGAL_LINE5,
          CURRENT_LAND_VALUE,
          CURRENT_IMPROVEMENT_VALUE,
          TAX_ASSESSMENT_YEAR,
          PREVIOUS_LAND_VALUE,
          PREVIOUS_IMPROVEMENT_VALUE,
          YEAR_BUILT,
          BIG_IMPROVEMENT_YEAR,
          TAX_LEVY,
          NEIGHBOURHOOD_CODE
        FROM `ca.vancouver.opendata.property.tax-report.2006-2010`
        UNION ALL
        SELECT
          PID,
          REPORT_YEAR,
          LEGAL_TYPE,
          FOLIO,
          LAND_COORDINATE,
          ZONING_DISTRICT,
          ZONING_CLASSIFICATION,
          LOT,
          PLAN,
          BLOCK,
          DISTRICT_LOT,
          FROM_CIVIC_NUMBER,
          TO_CIVIC_NUMBER,
          STREET_NAME,
          PROPERTY_POSTAL_CODE,
          NARRATIVE_LEGAL_LINE1,
          NARRATIVE_LEGAL_LINE2,
          NARRATIVE_LEGAL_LINE3,
          NARRATIVE_LEGAL_LINE4,
          NARRATIVE_LEGAL_LINE5,
          CURRENT_LAND_VALUE,
          CURRENT_IMPROVEMENT_VALUE,
          TAX_ASSESSMENT_YEAR,
          PREVIOUS_LAND_VALUE,
          PREVIOUS_IMPROVEMENT_VALUE,
          YEAR_BUILT,
          BIG_IMPROVEMENT_YEAR,
          TAX_LEVY,
          NEIGHBOURHOOD_CODE
        FROM `ca.vancouver.opendata.property.tax-report.2011-2015`
        UNION ALL
        SELECT
          PID,
          REPORT_YEAR,
          LEGAL_TYPE,
          FOLIO,
          LAND_COORDINATE,
          ZONING_DISTRICT,
          ZONING_CLASSIFICATION,
          LOT,
          PLAN,
          BLOCK,
          DISTRICT_LOT,
          FROM_CIVIC_NUMBER,
          TO_CIVIC_NUMBER,
          STREET_NAME,
          PROPERTY_POSTAL_CODE,
          NARRATIVE_LEGAL_LINE1,
          NARRATIVE_LEGAL_LINE2,
          NARRATIVE_LEGAL_LINE3,
          NARRATIVE_LEGAL_LINE4,
          NARRATIVE_LEGAL_LINE5,
          CURRENT_LAND_VALUE,
          CURRENT_IMPROVEMENT_VALUE,
          TAX_ASSESSMENT_YEAR,
          PREVIOUS_LAND_VALUE,
          PREVIOUS_IMPROVEMENT_VALUE,
          YEAR_BUILT,
          BIG_IMPROVEMENT_YEAR,
          TAX_LEVY,
          NEIGHBOURHOOD_CODE
        FROM `ca.vancouver.opendata.property.tax-report.2016-2019`
        UNION ALL
        SELECT
          PID,
          REPORT_YEAR,
          LEGAL_TYPE,
          FOLIO,
          LAND_COORDINATE,
          ZONING_DISTRICT,
          ZONING_CLASSIFICATION,
          LOT,
          PLAN,
          BLOCK,
          DISTRICT_LOT,
          FROM_CIVIC_NUMBER,
          TO_CIVIC_NUMBER,
          STREET_NAME,
          PROPERTY_POSTAL_CODE,
          NARRATIVE_LEGAL_LINE1,
          NARRATIVE_LEGAL_LINE2,
          NARRATIVE_LEGAL_LINE3,
          NARRATIVE_LEGAL_LINE4,
          NARRATIVE_LEGAL_LINE5,
          CURRENT_LAND_VALUE,
          CURRENT_IMPROVEMENT_VALUE,
          TAX_ASSESSMENT_YEAR,
          PREVIOUS_LAND_VALUE,
          PREVIOUS_IMPROVEMENT_VALUE,
          YEAR_BUILT,
          BIG_IMPROVEMENT_YEAR,
          TAX_LEVY,
          NEIGHBOURHOOD_CODE
        FROM `ca.vancouver.opendata.property.tax-report.2020-now`
  vocab:
    eventTimeColumn: REPORT_YEAR
