apiVersion: 1
kind: DatasetSnapshot
content:
  id: ca.vancouver.opendata.property.tax-report.2006-2010
  source:
    kind: root
    fetch:
      kind: url
      url: https://opendata.vancouver.ca/explore/dataset/property-tax-report-2006-2010/download/?format=csv&timezone=America/Los_Angeles&lang=en&use_labels_for_header=true&csv_separator=%3B
    read:
      kind: csv
      separator: ';'
      header: true
      nullValue: ''
    merge:
      kind: ledger
      primaryKey:
      - PID
  vocab:
    eventTimeColumn: TAX_ASSESSMENT_YEAR
