apiVersion: 1
kind: DatasetSnapshot
content:
  id: ca.vancouver.opendata.property.tax-report.2008
  rootPollingSource:
    fetch:
      kind: fetchUrl
      url: ftp://webftp.vancouver.ca/opendata/csv/property_tax_report_csv2008.zip
    prepare:
    - kind: decompress
      format: zip
    read:
      kind: csv
      header: true
      escape: '"'
      nullValue: ''
      multiLine: true
    merge:
      kind: ledger
      primaryKey:
      - PID
  vocabulary:
    eventTimeColumn: TAX_ASSESSMENT_YEAR
