apiVersion: 1
kind: Dataset
content:
  id: ca.vancouver.opendata.property.tax-report
  derivativeSource:
    inputs:
      - id: ca.vancouver.opendata.property.tax-report.2006
      - id: ca.vancouver.opendata.property.tax-report.2007
      - id: ca.vancouver.opendata.property.tax-report.2008
      - id: ca.vancouver.opendata.property.tax-report.2009
      - id: ca.vancouver.opendata.property.tax-report.2010
      - id: ca.vancouver.opendata.property.tax-report.2011
      - id: ca.vancouver.opendata.property.tax-report.2012
      - id: ca.vancouver.opendata.property.tax-report.2013
      - id: ca.vancouver.opendata.property.tax-report.2014
      - id: ca.vancouver.opendata.property.tax-report.2015
      - id: ca.vancouver.opendata.property.tax-report.2016
      - id: ca.vancouver.opendata.property.tax-report.2017
      - id: ca.vancouver.opendata.property.tax-report.2018
    steps:
      - view: ca.vancouver.opendata.property.tax-report
        query: >
          SELECT
            PID,
            LEGAL_TYPE,
            FOLIO,
            LAND_COORDINATE,
            null as ZONE_NAME,
            null as ZONE_CATEGORY,
            LOT,
            BLOCK,
            PLAN,
            DISTRICT_LOT,
            FROM_CIVIC_NUMBER,
            TO_CIVIC_NUMBER,
            STREET_NAME,
            PROPERTY_POSTAL_CODE,
            NARRATIVE_LEGAL_LINE1,
            NARRATIVE_LEGAL_LINE2,
            NARRATIVE_LEGAL_LINE3,
            NARRATIVE_LEGAL_LINE4,
            NARRATIVE_LEGAL_LINE5,
            CURRENT_LAND_VALUE,
            CURRENT_IMPROVEMENT_VALUE,
            2006 as TAX_ASSESSMENT_YEAR,
            null as PREVIOUS_LAND_VALUE,
            null as PREVIOUS_IMPROVEMENT_VALUE,
            YEAR_BUILT,
            BIG_IMPROVEMENT_YEAR,
            TAX_LEVY,
            NEIGHBOURHOOD_CODE
          FROM `ca.vancouver.opendata.property.tax-report.2006`
          UNION ALL
          SELECT
            PID,
            LEGAL_TYPE,
            FOLIO,
            LAND_COORDINATE,
            null as ZONE_NAME,
            null as ZONE_CATEGORY,
            LOT,
            BLOCK,
            PLAN,
            DISTRICT_LOT,
            FROM_CIVIC_NUMBER,
            TO_CIVIC_NUMBER,
            STREET_NAME,
            PROPERTY_POSTAL_CODE,
            NARRATIVE_LEGAL_LINE1,
            NARRATIVE_LEGAL_LINE2,
            NARRATIVE_LEGAL_LINE3,
            NARRATIVE_LEGAL_LINE4,
            NARRATIVE_LEGAL_LINE5,
            CURRENT_LAND_VALUE,
            CURRENT_IMPROVEMENT_VALUE,
            2007 as TAX_ASSESSMENT_YEAR,
            null as PREVIOUS_LAND_VALUE,
            null as PREVIOUS_IMPROVEMENT_VALUE,
            YEAR_BUILT,
            BIG_IMPROVEMENT_YEAR,
            TAX_LEVY,
            NEIGHBOURHOOD_CODE
          FROM `ca.vancouver.opendata.property.tax-report.2007`
          UNION ALL
          SELECT
            PID,
            LEGAL_TYPE,
            FOLIO,
            LAND_COORDINATE,
            null as ZONE_NAME,
            null as ZONE_CATEGORY,
            LOT,
            BLOCK,
            PLAN,
            DISTRICT_LOT,
            FROM_CIVIC_NUMBER,
            TO_CIVIC_NUMBER,
            STREET_NAME,
            PROPERTY_POSTAL_CODE,
            NARRATIVE_LEGAL_LINE1,
            NARRATIVE_LEGAL_LINE2,
            NARRATIVE_LEGAL_LINE3,
            NARRATIVE_LEGAL_LINE4,
            NARRATIVE_LEGAL_LINE5,
            CURRENT_LAND_VALUE,
            CURRENT_IMPROVEMENT_VALUE,
            2008 as TAX_ASSESSMENT_YEAR,
            null as PREVIOUS_LAND_VALUE,
            null as PREVIOUS_IMPROVEMENT_VALUE,
            YEAR_BUILT,
            BIG_IMPROVEMENT_YEAR,
            TAX_LEVY,
            NEIGHBOURHOOD_CODE
          FROM `ca.vancouver.opendata.property.tax-report.2008`
          UNION ALL
          SELECT
            PID,
            LEGAL_TYPE,
            FOLIO,
            LAND_COORDINATE,
            null as ZONE_NAME,
            null as ZONE_CATEGORY,
            LOT,
            BLOCK,
            PLAN,
            DISTRICT_LOT,
            FROM_CIVIC_NUMBER,
            TO_CIVIC_NUMBER,
            STREET_NAME,
            PROPERTY_POSTAL_CODE,
            NARRATIVE_LEGAL_LINE1,
            NARRATIVE_LEGAL_LINE2,
            NARRATIVE_LEGAL_LINE3,
            NARRATIVE_LEGAL_LINE4,
            NARRATIVE_LEGAL_LINE5,
            CURRENT_LAND_VALUE,
            CURRENT_IMPROVEMENT_VALUE,
            2009 as TAX_ASSESSMENT_YEAR,
            null as PREVIOUS_LAND_VALUE,
            null as PREVIOUS_IMPROVEMENT_VALUE,
            YEAR_BUILT,
            BIG_IMPROVEMENT_YEAR,
            TAX_LEVY,
            NEIGHBOURHOOD_CODE
          FROM `ca.vancouver.opendata.property.tax-report.2009`
          UNION ALL
          SELECT
            PID,
            LEGAL_TYPE,
            FOLIO,
            LAND_COORDINATE,
            null as ZONE_NAME,
            null as ZONE_CATEGORY,
            LOT,
            BLOCK,
            PLAN,
            DISTRICT_LOT,
            FROM_CIVIC_NUMBER,
            TO_CIVIC_NUMBER,
            STREET_NAME,
            PROPERTY_POSTAL_CODE,
            NARRATIVE_LEGAL_LINE1,
            NARRATIVE_LEGAL_LINE2,
            NARRATIVE_LEGAL_LINE3,
            NARRATIVE_LEGAL_LINE4,
            NARRATIVE_LEGAL_LINE5,
            CURRENT_LAND_VALUE,
            CURRENT_IMPROVEMENT_VALUE,
            2010 as TAX_ASSESSMENT_YEAR,
            null as PREVIOUS_LAND_VALUE,
            null as PREVIOUS_IMPROVEMENT_VALUE,
            YEAR_BUILT,
            BIG_IMPROVEMENT_YEAR,
            TAX_LEVY,
            NEIGHBOURHOOD_CODE
          FROM `ca.vancouver.opendata.property.tax-report.2010`
          UNION ALL
          SELECT
            PID,
            LEGAL_TYPE,
            FOLIO,
            LAND_COORDINATE,
            null as ZONE_NAME,
            null as ZONE_CATEGORY,
            LOT,
            BLOCK,
            PLAN,
            DISTRICT_LOT,
            FROM_CIVIC_NUMBER,
            TO_CIVIC_NUMBER,
            STREET_NAME,
            PROPERTY_POSTAL_CODE,
            NARRATIVE_LEGAL_LINE1,
            NARRATIVE_LEGAL_LINE2,
            NARRATIVE_LEGAL_LINE3,
            NARRATIVE_LEGAL_LINE4,
            NARRATIVE_LEGAL_LINE5,
            CURRENT_LAND_VALUE,
            CURRENT_IMPROVEMENT_VALUE,
            2011 as TAX_ASSESSMENT_YEAR,
            null as PREVIOUS_LAND_VALUE,
            null as PREVIOUS_IMPROVEMENT_VALUE,
            YEAR_BUILT,
            BIG_IMPROVEMENT_YEAR,
            TAX_LEVY,
            NEIGHBOURHOOD_CODE
          FROM `ca.vancouver.opendata.property.tax-report.2011`
          UNION ALL
          SELECT
            PID,
            LEGAL_TYPE,
            FOLIO,
            LAND_COORDINATE,
            null as ZONE_NAME,
            null as ZONE_CATEGORY,
            LOT,
            BLOCK,
            PLAN,
            DISTRICT_LOT,
            FROM_CIVIC_NUMBER,
            TO_CIVIC_NUMBER,
            STREET_NAME,
            PROPERTY_POSTAL_CODE,
            NARRATIVE_LEGAL_LINE1,
            NARRATIVE_LEGAL_LINE2,
            NARRATIVE_LEGAL_LINE3,
            NARRATIVE_LEGAL_LINE4,
            NARRATIVE_LEGAL_LINE5,
            CURRENT_LAND_VALUE,
            CURRENT_IMPROVEMENT_VALUE,
            2012 as TAX_ASSESSMENT_YEAR,
            null as PREVIOUS_LAND_VALUE,
            null as PREVIOUS_IMPROVEMENT_VALUE,
            YEAR_BUILT,
            BIG_IMPROVEMENT_YEAR,
            TAX_LEVY,
            NEIGHBOURHOOD_CODE
          FROM `ca.vancouver.opendata.property.tax-report.2012`
          UNION ALL
          SELECT
            PID,
            LEGAL_TYPE,
            FOLIO,
            LAND_COORDINATE,
            null as ZONE_NAME,
            null as ZONE_CATEGORY,
            LOT,
            BLOCK,
            PLAN,
            DISTRICT_LOT,
            FROM_CIVIC_NUMBER,
            TO_CIVIC_NUMBER,
            STREET_NAME,
            PROPERTY_POSTAL_CODE,
            NARRATIVE_LEGAL_LINE1,
            NARRATIVE_LEGAL_LINE2,
            NARRATIVE_LEGAL_LINE3,
            NARRATIVE_LEGAL_LINE4,
            NARRATIVE_LEGAL_LINE5,
            CURRENT_LAND_VALUE,
            CURRENT_IMPROVEMENT_VALUE,
            2013 as TAX_ASSESSMENT_YEAR,
            null as PREVIOUS_LAND_VALUE,
            null as PREVIOUS_IMPROVEMENT_VALUE,
            YEAR_BUILT,
            BIG_IMPROVEMENT_YEAR,
            TAX_LEVY,
            NEIGHBOURHOOD_CODE
          FROM `ca.vancouver.opendata.property.tax-report.2013`
          UNION ALL
          SELECT
            PID,
            LEGAL_TYPE,
            FOLIO,
            LAND_COORDINATE,
            ZONE_NAME,
            ZONE_CATEGORY,
            LOT,
            BLOCK,
            PLAN,
            DISTRICT_LOT,
            FROM_CIVIC_NUMBER,
            TO_CIVIC_NUMBER,
            STREET_NAME,
            PROPERTY_POSTAL_CODE,
            NARRATIVE_LEGAL_LINE1,
            NARRATIVE_LEGAL_LINE2,
            NARRATIVE_LEGAL_LINE3,
            NARRATIVE_LEGAL_LINE4,
            NARRATIVE_LEGAL_LINE5,
            CURRENT_LAND_VALUE,
            CURRENT_IMPROVEMENT_VALUE,
            2014 as TAX_ASSESSMENT_YEAR,
            PREVIOUS_LAND_VALUE,
            PREVIOUS_IMPROVEMENT_VALUE,
            YEAR_BUILT,
            BIG_IMPROVEMENT_YEAR,
            TAX_LEVY,
            NEIGHBOURHOOD_CODE
          FROM `ca.vancouver.opendata.property.tax-report.2014`
          UNION ALL
          SELECT
            PID,
            LEGAL_TYPE,
            FOLIO,
            LAND_COORDINATE,
            ZONE_NAME,
            ZONE_CATEGORY,
            LOT,
            BLOCK,
            PLAN,
            DISTRICT_LOT,
            FROM_CIVIC_NUMBER,
            TO_CIVIC_NUMBER,
            STREET_NAME,
            PROPERTY_POSTAL_CODE,
            NARRATIVE_LEGAL_LINE1,
            NARRATIVE_LEGAL_LINE2,
            NARRATIVE_LEGAL_LINE3,
            NARRATIVE_LEGAL_LINE4,
            NARRATIVE_LEGAL_LINE5,
            CURRENT_LAND_VALUE,
            CURRENT_IMPROVEMENT_VALUE,
            2015 as TAX_ASSESSMENT_YEAR,
            PREVIOUS_LAND_VALUE,
            PREVIOUS_IMPROVEMENT_VALUE,
            YEAR_BUILT,
            BIG_IMPROVEMENT_YEAR,
            TAX_LEVY,
            NEIGHBOURHOOD_CODE
          FROM `ca.vancouver.opendata.property.tax-report.2015`
          UNION ALL
          SELECT
            PID,
            LEGAL_TYPE,
            FOLIO,
            LAND_COORDINATE,
            ZONE_NAME,
            ZONE_CATEGORY,
            LOT,
            BLOCK,
            PLAN,
            DISTRICT_LOT,
            FROM_CIVIC_NUMBER,
            TO_CIVIC_NUMBER,
            STREET_NAME,
            PROPERTY_POSTAL_CODE,
            NARRATIVE_LEGAL_LINE1,
            NARRATIVE_LEGAL_LINE2,
            NARRATIVE_LEGAL_LINE3,
            NARRATIVE_LEGAL_LINE4,
            NARRATIVE_LEGAL_LINE5,
            CURRENT_LAND_VALUE,
            CURRENT_IMPROVEMENT_VALUE,
            2016 as TAX_ASSESSMENT_YEAR,
            PREVIOUS_LAND_VALUE,
            PREVIOUS_IMPROVEMENT_VALUE,
            YEAR_BUILT,
            BIG_IMPROVEMENT_YEAR,
            TAX_LEVY,
            NEIGHBOURHOOD_CODE
          FROM `ca.vancouver.opendata.property.tax-report.2016`
          UNION ALL
          SELECT
            PID,
            LEGAL_TYPE,
            FOLIO,
            LAND_COORDINATE,
            ZONE_NAME,
            ZONE_CATEGORY,
            LOT,
            BLOCK,
            PLAN,
            DISTRICT_LOT,
            FROM_CIVIC_NUMBER,
            TO_CIVIC_NUMBER,
            STREET_NAME,
            PROPERTY_POSTAL_CODE,
            NARRATIVE_LEGAL_LINE1,
            NARRATIVE_LEGAL_LINE2,
            NARRATIVE_LEGAL_LINE3,
            NARRATIVE_LEGAL_LINE4,
            NARRATIVE_LEGAL_LINE5,
            CURRENT_LAND_VALUE,
            CURRENT_IMPROVEMENT_VALUE,
            2017 as TAX_ASSESSMENT_YEAR,
            PREVIOUS_LAND_VALUE,
            PREVIOUS_IMPROVEMENT_VALUE,
            YEAR_BUILT,
            BIG_IMPROVEMENT_YEAR,
            TAX_LEVY,
            NEIGHBOURHOOD_CODE
          FROM `ca.vancouver.opendata.property.tax-report.2017`
          UNION ALL
          SELECT
            PID,
            LEGAL_TYPE,
            FOLIO,
            LAND_COORDINATE,
            ZONE_NAME,
            ZONE_CATEGORY,
            LOT,
            BLOCK,
            PLAN,
            DISTRICT_LOT,
            FROM_CIVIC_NUMBER,
            TO_CIVIC_NUMBER,
            STREET_NAME,
            PROPERTY_POSTAL_CODE,
            NARRATIVE_LEGAL_LINE1,
            NARRATIVE_LEGAL_LINE2,
            NARRATIVE_LEGAL_LINE3,
            NARRATIVE_LEGAL_LINE4,
            NARRATIVE_LEGAL_LINE5,
            CURRENT_LAND_VALUE,
            CURRENT_IMPROVEMENT_VALUE,
            2018 as TAX_ASSESSMENT_YEAR,
            PREVIOUS_LAND_VALUE,
            PREVIOUS_IMPROVEMENT_VALUE,
            YEAR_BUILT,
            BIG_IMPROVEMENT_YEAR,
            TAX_LEVY,
            NEIGHBOURHOOD_CODE
          FROM `ca.vancouver.opendata.property.tax-report.2018`
