apiVersion: 1
kind: DatasetSnapshot
content:
  id: org.geonames.cities.by-name
  source:
    kind: derivative
    inputs:
      - org.geonames.cities.raw
    transform:
      kind: sql
      engine: spark
      query: >
        SELECT
          explode(split(alternatenames, ",")) as alternatename,
          country_code, geonameid
          FROM `org.geonames.cities.raw`
          WHERE alternatenames IS NOT NULL
        UNION ALL
        SELECT
          name as alternatename,
          country_code, geonameid
          FROM `org.geonames.cities.raw`
        UNION ALL
        SELECT
          asciiname as alternatename,
          country_code, geonameid
          FROM `org.geonames.cities.raw`
