apiVersion: 1
kind: Dataset
content:
  id: org.geonames.altnames
  derivativeSource:
    inputs:
      - id: org.geonames.altnames.raw
    steps:
      - view: org.geonames.altnames
        query: >
          SELECT
            alternateNameId, geonameid, isolanguage, alternateName,
            CASE WHEN isPreferredName IS NULL THEN false ELSE isPreferredName > 0 END AS isPreferredName,
            CASE WHEN isShortName IS NULL THEN false ELSE isShortName > 0 END AS isShortName,
            CASE WHEN isColloquial IS NULL THEN false ELSE isColloquial > 0 END AS isColloquial,
            CASE WHEN isHistoric IS NULL THEN false ELSE isHistoric > 0 END AS isHistoric,
            from, to
          FROM `org.geonames.altnames.raw`
