apiVersion: 1
kind: DatasetSnapshot
content:
  id: org.geonames.cities.by-name
  derivativeSource:
    inputs:
      - id: org.geonames.cities.raw
    steps:
      - kind: sparkSQL
        query: >
          SELECT
            explode(split(alternatenames, ",")) as alternatename,
            country_code, geonameid
            FROM `org.geonames.cities.raw`
            WHERE alternatenames IS NOT NULL
          UNION ALL
          SELECT
            name as alternatename,
            country_code, geonameid
            FROM `org.geonames.cities.raw`
          UNION ALL
          SELECT
            asciiname as alternatename,
            country_code, geonameid
            FROM `org.geonames.cities.raw`
