apiVersion: 1
kind: DatasetSnapshot
content:
  id: org.geonames.cities
  source:
    kind: derivative
    inputs:
      - id: org.geonames.cities.raw
    transform:
      engine: sparkSQL
      query: >
        SELECT
          geonameid, name, asciiname, country_code, population, timezone,
          ST_Point(
            cast(longitude as decimal(9,6)),
            cast(latitude as decimal(9,6))
          ) as location_wgs84,
          elevation
        FROM `org.geonames.cities.raw`
