apiVersion: 1
kind: DatasetSnapshot
content:
  id: us.cityofnewyork.data.zipcode-boundaries
  source:
    kind: root
    fetch:
      kind: url
      url: https://data.cityofnewyork.us/api/views/i8iw-xf4u/files/YObIR0MbpUVA0EpQzZSq5x55FzKGM2ejSeahdvjqR20?filename=ZIP_CODE_040114.zip
    read:
      kind: shapefile
    merge:
      kind: snapshot
      primaryKey:
      - ZIPCODE
