apiVersion: 1
kind: DatasetSnapshot
content:
  id: ca.vancouver.opendata.property.block-outlines
  rootPollingSource:
    fetch:
      kind: fetchUrl
      url: ftp://webftp.vancouver.ca/OpenData/shape/shape_property_information.zip
    read:
      kind: shapefile
      subPathRegex: block_outlines.*
    preprocess:
      - kind: sparkSQL
        query: >
          SELECT
            ST_Transform(geometry, "epsg:3157", "epsg:4326") as geometry
          FROM input
    merge:
      # TODO
      kind: append