apiVersion: 1
kind: Dataset
content:
  id: com.naturalearthdata.admin0.countries
  derivativeSource:
    inputs:
      - id: com.naturalearthdata.admin0.countries.10m
      - id: com.naturalearthdata.admin0.countries.50m
        mode: batch
      - id: com.naturalearthdata.admin0.countries.110m
        mode: batch
    steps:
      - view: com.naturalearthdata.admin0.countries
        query: >
          SELECT
            c10.admin,
            c10.iso_a2,
            c10.iso_a3,
            c10.geometry as geometry_10m,
            c50.geometry as geometry_50m,
            c110.geometry as geometry_110m
          FROM `com.naturalearthdata.admin0.countries.10m` as c10
          LEFT JOIN `com.naturalearthdata.admin0.countries.50m` as c50
            ON c10.admin = c50.admin
          LEFT JOIN `com.naturalearthdata.admin0.countries.50m` as c110
            ON c10.admin = c110.admin
