apiVersion: 1
kind: Dataset
content:
  id: com.naturalearthdata.admin0.countries.110m
  rootPollingSource:
    fetch:
      kind: fetchUrl
      url: https://naciscdn.org/naturalearth/110m/cultural/ne_110m_admin_0_countries.zip
    read:
      kind: shapefile
    merge:
      kind: snapshot
      primaryKey:
      - ISO_A2
