apiVersion: 1
kind: DatasetSnapshot
content:
  id: com.naturalearthdata.admin0.countries.50m
  source:
    kind: root
    fetch:
      kind: url
      url: https://naciscdn.org/naturalearth/50m/cultural/ne_50m_admin_0_countries.zip
    read:
      kind: shapefile
    merge:
      kind: snapshot
      primaryKey:
      - ISO_A2