apiVersion: 1
kind: Dataset
content:
  id: us.cityofnewyork.data.ems-incident-dispatch
  derivativeSource:
    inputs:
      - id: us.cityofnewyork.data.ems-incident-dispatch.raw
    steps:
      - view: us.cityofnewyork.data.ems-incident-dispatch
        query: >
          SELECT
            cad_incident_id,
            to_timestamp(incident_datetime, "MM/dd/yyyy h:mm:ss a") AS incident_datetime,
            initial_call_type,
            initial_severity_level_code,
            final_call_type,
            final_severity_level_code,
            to_timestamp(first_assignment_datetime, "MM/dd/yyyy h:mm:ss a") AS first_assignment_datetime,
            (valid_dispatch_rspns_time_indc = "Y") AS valid_dispatch_rspns_time_indc,
            dispatch_response_seconds_qy,
            to_timestamp(first_activation_datetime, "MM/dd/yyyy h:mm:ss a") AS first_activation_datetime,
            to_timestamp(first_on_scene_datetime, "MM/dd/yyyy h:mm:ss a") AS first_on_scene_datetime,
            (valid_incident_rspns_time_indc = "Y") AS valid_incident_rspns_time_indc,
            incident_response_seconds_qy,
            incident_travel_tm_seconds_qy,
            to_timestamp(first_to_hosp_datetime, "MM/dd/yyyy h:mm:ss a") AS first_to_hosp_datetime,
            to_timestamp(first_hosp_arrival_datetime, "MM/dd/yyyy h:mm:ss a") AS first_hosp_arrival_datetime,
            to_timestamp(incident_close_datetime, "MM/dd/yyyy h:mm:ss a") AS incident_close_datetime,
            (held_indicator = "Y") AS held_indicator,
            incident_disposition_code,
            borough,
            incident_dispatch_area,
            zipcode,
            policeprecinct,
            citycouncildistrict,
            communitydistrict,
            communityschooldistrict,
            congressionaldistrict,
            (reopen_indicator = "Y") AS reopen_indicator,
            (special_event_indicator = "Y") AS special_event_indicator,
            (standby_indicator = "Y") AS standby_indicator,
            (transfer_indicator = "Y") AS transfer_indicator
          FROM `us.cityofnewyork.data.ems-incident-dispatch.raw`
