apiVersion: 1
kind: DatasetSnapshot
content:
  id: ca.vancouver.opendata.zoning-districts
  source:
    kind: root
    fetch:
      kind: url
      url: ftp://webftp.vancouver.ca/OpenData/shape/zoning_districts_shp.zip
    read:
      kind: shapefile
    preprocess:
      engine: sparkSQL
      query: >
        SELECT
          ST_Transform(geometry, "epsg:3157", "epsg:4326") as geometry,
          ZONE_NAME,
          CATEGORY
        FROM input
    merge:
      # TODO
      kind: append